### ISSUE TITLE
Replicating results

### ISSUE THREAD

**Issue by vedantbhatia** [shizhouxing/DialogueDiscourseParsing#1]
Hi,

Can you please tell me what duration/epochs and what dataset split you used to achieve the results in your paper? Should running the code with python main.py --is_train be enough to replicate the results?

Thanks!

**Comment by shizhouxing** [comment]
Hi Vedant,

* Please run it for about 50 epochs, and you are expected to see a comparable result as the one in the paper (results may vary a little due to the random initialization). `python main.py --is_train` is used to train the full model.

* The STAC corpus has already been splitted  into training/test sets. Please just use them.

**Comment by vedantbhatia** [comment]
Thank you for the prompt reply!

On the STAC website, there are two versions available, the linguistic and the situated corpora. Which did you use? Also, did you simply concatenate the different seasons into one json?

**Comment by shizhouxing** [comment]
1. I used the linguistic one
2. Yes, I concatenated the different seasons
